# Lingbase 部署配置

[remote.gpu-server]
host = "67.0.0.5"
user = "etsme"
port = 22
password = "l7OiD3QuWNI#sC"
description = "RTX 4090 GPU Server"
arch = "x86_64"
lib_dir = "cuda"

[remote.arm-server]
host = "192.168.0.124"
user = "firefly"
port = 22
password = "firefly"
description = "ARM64 Server"
arch = "aarch64"
lib_dir = "aarch64"