# Lingbase 部署配置

[remote.x86-server]
host = "67.0.0.2"
user = "etsme"
port = 22
password = "etsme"
arch = "x86_64"
lib_dir = "x86_64-cpu"

[remote.gpu-server]
host = "67.0.0.5"
user = "etsme"
port = 22
password = "l7OiD3QuWNI#sC"
description = "RTX 4090 GPU Server"
arch = "x86_64"
lib_dir = "x86_64-cuda"

[remote.arm-server]
host = "192.168.0.124"
user = "firefly"
port = 22
password = "firefly"
description = "ARM64 Server"
arch = "aarch64"
lib_dir = "aarch64-rk-cpu"

[remote.RK3588-server]
host = "192.168.0.124"
user = "firefly"
port = 22
password = "firefly"
description = "Firefly RK3588 NPU Server - use rknn3-aarch64 lib"
arch = "aarch64"
lib_dir = "rknn3-aarch64"